# Generated by Django 4.2.5 on 2025-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('strike', models.IntegerField()),
                ('ce', models.FloatField()),
                ('ce_diff', models.FloatField()),
                ('pe', models.FloatField()),
                ('pe_diff', models.FloatField()),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='OptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=60)),
                ('strike_price', models.IntegerField()),
                ('option_type', models.CharField(choices=[('PE', 'Put'), ('CE', 'Call')], max_length=2)),
                ('open_interest', models.FloatField(default=0)),
                ('previous_open_interest', models.FloatField(default=0)),
                ('oi_diff', models.FloatField(default=0)),
            ],
        ),
    ]
